---
# Source: mysql-innodbcluster/templates/cluster_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: innodb1-cluster-secret
  namespace: innodbcluster
stringData:
  rootUser: "root"
  rootHost: "%"
  rootPassword: "root"
