---
# Source: mysql-innodbcluster/templates/deployment_cluster.yaml
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: innodb1
  namespace: innodbcluster
spec:
  instances: 3
  tlsUseSelfSigned: true
  router:
    instances: 1


  secretName: innodb1-cluster-secret
  imagePullPolicy : IfNotPresent
  baseServerId: 1000
  version: 8.4.0
  serviceAccountName: innodb1-sa
  # mycnf
  # datadirVolumeClaimTemplate
  datadirVolumeClaimTemplate:
    storageClassName: "mylocalsc1"
  # Keyring
  # Init DB
  # Backup Profiles
  # Backup Schedules
  # Pod Spec
  # Pod Labels
  # Pod Annotations
  # Logs
  # Service
  # Metrics
  # Read Replicas
